// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zatxkyfxfnrrigedmfgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdHhreWZ4Zm5ycmlnZWRtZmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDQyOTUsImV4cCI6MjA2NDEyMDI5NX0.m33vSj09ZMmlHozg5m3isPhY1__BHIJmne43nOTLFWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);